### ISSUE TITLE
Intellij setup question

### ISSUE THREAD

**Issue by evandor** [jan0sch/pfhais#1]
Hi and thanks a lot for sharing your thoughts and work! 

Just in case you are using Intellij Idea as IDE: do you have any special setup in place to make the project compile? I keep getting a "No implicits found for parameters..." in TranslationTest.scala, for example at

`RefType.applyRef[LanguageCode](l)`

"sbt clean test" does not have an issue, though. I do not have too much experience with sbt, unfortunately, but I can see quite a few compiler options in the build setup...

Any hint highly appreciated (and thanks for writing that book, highly inspiring ;))

**Comment by jan0sch** [comment]
Hi,

to be honest: I haven't used Intellj Idea for Scala in nearly a year now. ;-) My main reason for dropping it was exactly as you described: Showing errors when the code actually compiled fine.

Usually Idea should import the project if you open the `impure/build.sbt` or `pure/build.sbt`. So there would be two projects.

If you still cannot get it to work then you could maybe checkout scala metals (with VSCode) which is somewhere in between a simple editor setup and a full blown IDE.

Kind regards,

Jens

**Comment by evandor** [comment]
Hi Jens, thanks for your input, I'll give it another try (with Idea and VSCode).
If I'll find out something, I'll comment on this issue (but for now, I'll close it).

All the best
Carsten

**Comment by jan0sch** [comment]
Cool, thanks. :+1:
