### ISSUE TITLE
Test Cases Compilation Error

### ISSUE THREAD

**Issue by isarwarfp** [jan0sch/pfhais#4]
1. 
Error:(20, 16) BaseSpec is already defined as class BaseSpec
abstract class BaseSpec extends WordSpec with MustMatchers with ScalaCheckPropertyChecks {}
2.
Error:(20, 16) Companions 'class BaseSpec' and 'object BaseSpec' must be defined in same file:
  Found in /Users/imransarwar/git/pfhais/impure/src/test/scala/com/wegtam/books/pfhais/BaseSpec.scala and /Users/imransarwar/git/pfhais/impure/src/it/scala/com/wegtam/books/pfhais/impure/BaseSpec.scala
abstract class BaseSpec extends WordSpec with MustMatchers with ScalaCheckPropertyChecks {}
3.
Error:(23, 8) TypeGenerators is already defined as object TypeGenerators
object TypeGenerators {

**Comment by jan0sch** [comment]
Is this still relevant? If yes, what is your setup? The book source is intended to be run via `sbt`, it might work with idea but I haven't tested that.

**Comment by isarwarfp** [comment]
My fault, I was trying to run TestCases from Intellij Run and then get the above error.
But running tests with sbt all test passed !!!

```
[info] ScalaTest
[info] Run completed in 14 seconds, 972 milliseconds.
[info] Total number of tests run: 28
[info] Suites: completed 6, aborted 0
[info] Tests: succeeded 28, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 28, Failed 0, Errors 0, Passed 28
[success] Total time: 83 s, completed Nov 18, 2020 9:54:16 PM
```
Thanks
